config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :keywords , only: :index do
        post 'upload'
      end
    end
  end
  resources :reports
  resources :keywords , only: :index do
    get :autocomplete_word_word, :on => :collection
    collection do
      post  'upload'
      get   'upload_file'
    end
  end

  
  get "/resque/users/sign_in", to: redirect("/users/sign_in") 
  
  authenticate :user do 
    mount Resque::Server, :at => "/resque"
  end

end

app/models/report.rb
class Report < ActiveRecord::Base
	
	belongs_to :user #report created by this user

	serialize :report, JSON

	# generate report_field automatically before save report
	
	before_save :fill_report

	def fill_report
	  self.report = Word.order(word: :asc).as_json
	end 
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :reports
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/word.rb
class Word < ActiveRecord::Base
	serialize :top_adwords_urls,Array
	serialize :right_adwords_urls,Array
	serialize :no_adwords_urls,Array


end

app/controllers/api/v1/keywords_controller.rb
class Api::V1::KeywordsController < ApplicationController
	before_action :doorkeeper_authorize!
	

	include KeywordsConcern
	
end

app/controllers/api/v1/reports_controller.rb
class Api::V1::ReportsController < ApplicationController

	def show	
	end

	def index
	end

	def create
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  
end

app/controllers/concerns/keywords_concern.rb
require 'csv'

module KeywordsConcern
    extend ActiveSupport::Concern

    def upload
      if ["text/csv","application/vnd.ms-excel"].include? params[:keys].content_type
        keys = CSV.parse(params[:keys].read,{:col_sep => ";", :headers => false,  :skip_blanks => true}).map
        if keys.size.between?(1, 1000)  
          # create background worker search and add it to queue 
          Resque.enqueue(GoogleSearch,keys)
          render :text => "Upload successful , search processing has started"
        else
          render :text => "Number of keywords Out of range max 1000"
        end
      else
       render text: "Failed to upload"
      end
    end

end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
	   
	before_action :authenticate_user!

	autocomplete :word, :word

	include KeywordsConcern

    def index
      unless params[:key].blank?
      	case params[:type]
      	  when '1' then
      	  	Word.where('word LIKE ?', "%#{params[:key]}%").all
      	  when '2' then
      	  	Word.where('top_adwords_urls LIKE ? or right_adwords_urls  LIKE ? ', "%#{params[:key]}%","%#{params[:key]}%").all
      	end		
      else	
    	@result = []
      end
    end

    def upload_file
    end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

	before_action :authenticate_user!

  def create
  	if current_user
        Report.create(:user_id=>current_user.id)
    end
    redirect_to action: :index
  end

  def index
  	@reports = current_user.reports
  end

  def show
  	@report = Report.find(params[:id])
  end
end

app/helpers/api/v1/keywords_helper.rb
module Api::V1::KeywordsHelper
end

app/helpers/api/v1/reports_helper.rb
module Api::V1::ReportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/keywords/index.html.haml
= form_for "keywords",url: keywords_path,method: "get" do |f|
  = f.autocomplete_field :key, autocomplete_word_word_keywords_path
  = f.select :type,[["keywords",1],["Adwords urls",2],["urls",3]]
  = f.label "Number Of Result"
  = f.text_field :nb_result
  = f.submit("Find")
- if @result.size
  - @result.map do |p|
    = p.html_safe

app/views/keywords/upload_file.html.haml
= form_tag upload_keywords_path ,:method => 'Post',multipart: true  do
  = file_field_tag :keys, accept: '.csv'
  = submit_tag("send")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SeoProject
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
  %body
    %nav.navbar.navbar-inverse.navbar-static-top
      %a.navbar-brand
        = current_user.email if current_user
      %ul.nav.navbar-top-
        %li
          %ul.nav.navbar-nav
            %li
            %li
              = link_to "Sign out", destroy_user_session_path, :method => :delete
            %li
              %a{:href=>upload_file_keywords_path}
                Upload
            %li.dropdown
              %a.dropdown-toggle{:'data-toggle'=>"dropdown",:role=>"button",:'aria-haspopup'=>"true",:'aria-expanded'=>"false"}
                Report
                %span.caret
              %ul.dropdown-menu
                %li
                  = link_to "Create", reports_path(current_user.id), method: :post
                %li.divider{:role=>"separator"}
                %li  
                  %a{:href=>reports_path}
                    History            
    -unless notice.blank?
      %p.notice= notice
    -unless alert.blank?
      %p.alert= alert
    = yield

app/views/reports/index.html.haml
%table.table
  %tr
    %th
      Date
    %th
      Created by
    %th
      Number Of words
    %th
  - @reports.each do |row|
    %tr
      %td= row.created_at
      %td= row.user.email
      %td= row.report.size
      %td
        %a{:href=>report_path(row.id)}
          View

app/views/reports/show.html.haml
%h4
  Report created by :
  = @report.user.email
  at
  = @report.created_at
%table.table
  %tr
    %th
      Word
    %th
      Number Of results
    %th
      Number Of Adwords
  - @report.report.each do |row|
    %tr
      %td= row["word"]
      %td= row["all_results_count"]
      %td= row["nb_adwords_all"]